version: '3.9'

networks:
  default:
    name: nextjs-otel
    driver: bridge

services:
  ## Open Telemetry Services
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - '16686:16686'
      - '14250'

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.56.0
    command: ['--config=/etc/otelcol-config.yml']
    volumes:
      - ./config/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - '4317:4317'
      - '4318:4318'
      - '9464'
      - '8888'
    depends_on:
      - jaeger

  ## Application Services
  app:
    image: app
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otelcol:4317
      - OTEL_SERVICE_NAME=app-backend
    depends_on:
      - otelcol
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 1s
      timeout: 5s
      retries: 60
