import type { NextPage } from 'next';
import Head from 'next/head';
import { useQuery } from 'react-query';
import styles from '../styles/Home.module.css';

const fetchHello = async (): Promise<{ name: string }> => {
  const response = await fetch('/api/hello');

  return response.json();
};

const Home: NextPage = () => {
  const { data: hello = { name: '' } } = useQuery('hello', fetchHello);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Otel Instrumentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome {hello.name} to the <a href="https://nextjs.org">Next.js!</a> Otel Instrumentation
        </h1>
      </main>
    </div>
  );
};

export default Home;
